# Generated by Django 3.2 on 2022-07-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220706_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='onSale',
            field=models.BooleanField(default=False),
        ),
    ]
