# Generated by Django 3.2 on 2022-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220622_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_play_time',
        ),
        migrations.AddField(
            model_name='product',
            name='play_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
